### ISSUE TITLE
Search inside formatted JSON appears to be broken

### ISSUE THREAD

**Issue by UrsaDK** [acrogenesis/JSONAce#3]
Brilliant extensions, unfortunately it appears that I'm unable to search formatted JSON for a given string.

How to replicate:
1. Install and activate the extension
2. Go to http://echo.jsontest.com/test-key-1/test-value-1/test-key-2/test-value-2/test-key-3/test-value-3
3. Start a search with Cmd-F and enter a search string, eg: `test`

At this point your browser should highlight all instances of the word `test` in the displayed JSON, however the navigation between highlighted instances (Prev/Next) is broken and there is no highlighting of the current search instance.

**Comment by acrogenesis** [comment]
@UmkaDK thanks for the heads up! It's already fixed in version `1.7` (released seconds ago). I'll close this issue if you are still having trouble please reopen it. 

If it's not updating automatically remember to restart Safari.

**Comment by UrsaDK** [comment]
Perfect timing! :) Updated to version 1.7 and the problem has gone away. Thanks a lot @acrogenesis!
